spring:
  security:
    user: # 기본 name/password설정
      name: user
      password: 1234
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpalogin;  #ex)jdbc:h2:~/jpalogin (최소 한번) jdbc:h2:tcp://localhost/~/jpalogin;
    username: sa
    password:
    driver-class-name: org.h2.Driver



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org:
    zerock:
      security: debug
    springframework:
      security:
        web: debug

  # org.hibernate.type: trace
#  org:
#    springframework:
#      security:
#        web: trace
#
#    zerock: debug

